name: Test CICD

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  windows-job:
    name: Test on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Sửa '@v3v3' thành '@v3'

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # Sửa '17Tets' thành '17'

      - name: Build and Test on Windows
        run: mvn clean verify  # Sửa 'run:mvn' thành 'run: mvn'
